import { useMemo, useState } from "react"
import { Download, FileBarChart, MailCheck, MousePointerClick, Send, TrendingUp, Users } from "lucide-react"
import { toast } from "sonner"

import { Button } from "@/components/ui/button"
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select"
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table"
import { useEmailMarketingStore } from "../EmailMarketingStore"
import { downloadEmailMarketingReport } from "../emailMarketingApi"
import { EmptyPanel, MetricCard, ModulePage, PageContainer, PageHeading, StatusPill } from "../components/PageElements"
import { aggregateCampaigns, number, rate } from "./analyticsUtils"

export function ReportsPage() {
  const { campaigns, subscribers, suppressions } = useEmailMarketingStore()
  const [range, setRange] = useState("30")
  const [target, setTarget] = useState("campaigns")
  const [format, setFormat] = useState("csv")
  const totals = useMemo(() => aggregateCampaigns(campaigns), [campaigns])
  const subscribed = subscribers.filter((item) => item.status === "subscribed").length
  const exportReport = async () => {
    try {
      const params = new URLSearchParams({
        target,
        format,
        days: range === "all" ? "366" : range,
      })
      await downloadEmailMarketingReport(params)
      toast.success("Report exported from CRM data")
    } catch {
      toast.error("Report could not be exported.")
    }
  }
  return <ModulePage><PageContainer><PageHeading title="Reports center" description="Review operational summaries and export campaign, audience, and deliverability data." actions={<Select value={range} onValueChange={setRange}><SelectTrigger className="w-40"><SelectValue /></SelectTrigger><SelectContent><SelectItem value="7">Last 7 days</SelectItem><SelectItem value="30">Last 30 days</SelectItem><SelectItem value="90">Last 90 days</SelectItem><SelectItem value="all">All time</SelectItem></SelectContent></Select>} />
    <section className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><MetricCard label="Sent" value={number(totals.sent)} helper={`${number(totals.delivered)} delivered`} icon={<Send className="h-5 w-5" />} /><MetricCard label="Open rate" value={rate(totals.opens, totals.delivered)} helper={`${number(totals.opens)} opens`} icon={<MailCheck className="h-5 w-5" />} tone="success" /><MetricCard label="Click rate" value={rate(totals.clicks, totals.delivered)} helper={`${number(totals.clicks)} clicks`} icon={<MousePointerClick className="h-5 w-5" />} /><MetricCard label="Net audience" value={subscribed} helper={`${subscribers.length} total contacts`} icon={<Users className="h-5 w-5" />} tone="muted" /></section>
    <section className="grid gap-6 lg:grid-cols-[minmax(0,1fr)_380px]"><div className="rounded-2xl border bg-card"><div className="border-b p-5"><h3 className="font-semibold">Campaign report</h3><p className="mt-1 text-xs text-muted-foreground">One-row performance summary for every campaign.</p></div>{campaigns.length ? <div className="overflow-x-auto"><Table><TableHeader><TableRow><TableHead>Campaign</TableHead><TableHead>Status</TableHead><TableHead>Sent</TableHead><TableHead>Delivered</TableHead><TableHead>Open rate</TableHead><TableHead>Click rate</TableHead></TableRow></TableHeader><TableBody>{campaigns.map((item) => <TableRow key={item.id}><TableCell className="font-medium">{item.name}</TableCell><TableCell><StatusPill status={item.status} /></TableCell><TableCell>{number(item.metrics.sent)}</TableCell><TableCell>{number(item.metrics.delivered)}</TableCell><TableCell>{rate(item.metrics.opens, item.metrics.delivered)}</TableCell><TableCell>{rate(item.metrics.clicks, item.metrics.delivered)}</TableCell></TableRow>)}</TableBody></Table></div> : <div className="p-5"><EmptyPanel title="No campaign report yet" description="Campaign summaries appear here once campaigns are created." /></div>}</div>
      <aside className="space-y-5"><div className="rounded-2xl border bg-card p-5"><FileBarChart className="h-8 w-8 text-primary" /><h3 className="mt-4 font-semibold">Export a report</h3><p className="mt-1 text-sm text-muted-foreground">Download workspace-scoped data generated by the CRM backend.</p><div className="mt-5 space-y-3"><Select value={target} onValueChange={setTarget}><SelectTrigger><SelectValue /></SelectTrigger><SelectContent><SelectItem value="campaigns">Campaign report</SelectItem><SelectItem value="audience">Audience report</SelectItem><SelectItem value="deliverability">Deliverability report</SelectItem><SelectItem value="automations">Automation report</SelectItem></SelectContent></Select><Select value={format} onValueChange={setFormat}><SelectTrigger><SelectValue /></SelectTrigger><SelectContent><SelectItem value="csv">CSV spreadsheet</SelectItem><SelectItem value="json">JSON data</SelectItem></SelectContent></Select><Button className="w-full" onClick={exportReport}><Download className="mr-2 h-4 w-4" />Export report</Button></div></div><div className="rounded-2xl border bg-muted/40 p-5"><TrendingUp className="h-7 w-7 text-primary" /><h3 className="mt-3 font-semibold">Audience health</h3><dl className="mt-4 space-y-3 text-sm"><div className="flex justify-between"><dt className="text-muted-foreground">Subscribed</dt><dd className="font-medium">{subscribed}</dd></div><div className="flex justify-between"><dt className="text-muted-foreground">Suppressed</dt><dd className="font-medium">{suppressions.length}</dd></div><div className="flex justify-between"><dt className="text-muted-foreground">Growth rate</dt><dd className="font-medium">{subscribers.length ? "100.00%" : "0.00%"}</dd></div></dl></div></aside></section>
  </PageContainer></ModulePage>
}
